/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.view;

import org.example.view.FormAddStudent;
import org.example.view.FormAddTeacher;
import org.example.view.FormAddProgram;
import org.example.view.FormLogin;

/**
 *
 * @author pavel
 */
public class FormAdminCenter extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(FormAdminCenter.class.getName());

    /**
     * Creates new form FormAdminCenter
     */
    public FormAdminCenter() {
        initComponents();

        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();

        btnAddStudent = new javax.swing.JButton();
        btnAddTeacher = new javax.swing.JButton();
        btnAddProgram = new javax.swing.JButton();

        btnViewStudents = new javax.swing.JButton();
        btnViewTeachers = new javax.swing.JButton();

        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Администратор центра");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18));
        lblTitle.setText("Панель администратора центра");

        btnAddStudent.setText("Добавить студента");
        btnAddStudent.addActionListener(this::btnAddStudentActionPerformed);

        btnAddTeacher.setText("Добавить преподавателя");
        btnAddTeacher.addActionListener(this::btnAddTeacherActionPerformed);

        btnAddProgram.setText("Добавить программу");
        btnAddProgram.addActionListener(this::btnAddProgramActionPerformed);

        btnViewStudents.setText("Показать студентов");

        btnViewTeachers.setText("Показать преподавателей");

        btnLogout.setText("Выйти");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout layout =
                new javax.swing.GroupLayout(getContentPane());

        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                                        .addComponent(lblTitle)

                                        .addComponent(btnAddStudent,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                250,
                                                Short.MAX_VALUE)

                                        .addComponent(btnAddTeacher,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)

                                        .addComponent(btnAddProgram,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)

                                        .addComponent(btnViewStudents,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)

                                        .addComponent(btnViewTeachers,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)

                                        .addComponent(btnLogout,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))

                                .addContainerGap(35, Short.MAX_VALUE))
        );

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()

                                .addGap(20, 20, 20)

                                .addComponent(lblTitle)

                                .addGap(25, 25, 25)

                                .addComponent(btnAddStudent)

                                .addGap(18, 18, 18)

                                .addComponent(btnAddTeacher)

                                .addGap(18, 18, 18)

                                .addComponent(btnAddProgram)

                                .addGap(18, 18, 18)

                                .addComponent(btnViewStudents)

                                .addGap(18, 18, 18)

                                .addComponent(btnViewTeachers)

                                .addGap(25, 25, 25)

                                .addComponent(btnLogout)

                                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed

        FormAddStudent addStudentForm = new FormAddStudent();
        addStudentForm.setVisible(true);

    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeacherActionPerformed

        FormAddTeacher addTeacherForm = new FormAddTeacher();
        addTeacherForm.setVisible(true);

    }//GEN-LAST:event_btnAddTeacherActionPerformed

    private void btnAddProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProgramActionPerformed

        FormAddProgram addProgramForm = new FormAddProgram();
        addProgramForm.setVisible(true);

    }//GEN-LAST:event_btnAddProgramActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        this.dispose();

        FormLogin loginForm = new FormLogin();
        loginForm.setVisible(true);

    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

        } catch (ReflectiveOperationException |
                 javax.swing.UnsupportedLookAndFeelException ex) {

            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
                new FormAdminCenter().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JButton btnAddProgram;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnAddTeacher;

    private javax.swing.JButton btnLogout;

    private javax.swing.JButton btnViewStudents;
    private javax.swing.JButton btnViewTeachers;

    private javax.swing.JLabel lblTitle;

    // End of variables declaration//GEN-END:variables
}